// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRDAW9UJBuzwcPa8SazVedv1AfcZ9yaPs',
    appId: '1:308935094536:web:2093f2463600b2b7d87cbd',
    messagingSenderId: '308935094536',
    projectId: 'harbour-final',
    authDomain: 'harbour-final.firebaseapp.com',
    storageBucket: 'harbour-final.appspot.com',
    measurementId: 'G-V1ZLWL3BK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl302diXzcpep2og086Jb-5Sq-XayL0zg',
    appId: '1:308935094536:android:b7cdabe0bdf365add87cbd',
    messagingSenderId: '308935094536',
    projectId: 'harbour-final',
    storageBucket: 'harbour-final.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-6NDLo0RNfJFLAx5BMKWHC360R6PY2RE',
    appId: '1:308935094536:ios:98e25cd04f04d873d87cbd',
    messagingSenderId: '308935094536',
    projectId: 'harbour-final',
    storageBucket: 'harbour-final.appspot.com',
    androidClientId: '308935094536-84ag5jk3r36pkch5r7bcbq56c1mpvr6k.apps.googleusercontent.com',
    iosClientId: '308935094536-j9m4phl8o4qakcop8121utvuolpcfpee.apps.googleusercontent.com',
    iosBundleId: 'com.XSol.harbour',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-6NDLo0RNfJFLAx5BMKWHC360R6PY2RE',
    appId: '1:308935094536:ios:e81dcd92521a088cd87cbd',
    messagingSenderId: '308935094536',
    projectId: 'harbour-final',
    storageBucket: 'harbour-final.appspot.com',
    androidClientId: '308935094536-84ag5jk3r36pkch5r7bcbq56c1mpvr6k.apps.googleusercontent.com',
    iosClientId: '308935094536-hnrp39gu1i9593q1jdcljbiecaiasuu2.apps.googleusercontent.com',
    iosBundleId: 'com.XSol.harbour.RunnerTests',
  );
}
